CREATE DATABASE dbprueba1aasd;
CREATE OR REPLACE DATABASE dbprueba1aasd;
CREATE OR REPLACE DATABASE dbprueba1aasd1;
CREATE OR REPLACE DATABASE dbprueba1aasd2;
CREATE OR REPLACE DATABASE dbprueba1aasd3;