<orReplace> ::= 
<ifNotExists> ::= R_IF R_NOT R_EXISTS 
<idOrString> ::= ID 
<createOwner> ::= R_OWNER S_IGUAL STRING 
<createMode> ::= R_MODE S_IGUAL INTEGER 
<createOpts> ::= <orReplace> R_DATABASE <ifNotExists> <idOrString> <createOwner> <createMode> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmt> 
<orReplace> ::= 
<ifNotExists> ::= R_IF R_NOT R_EXISTS 
<idOrString> ::= ID 
<createOwner> ::= R_OWNER S_IGUAL STRING 
<createMode> ::= R_MODE S_IGUAL INTEGER 
<createOpts> ::= <orReplace> R_DATABASE <ifNotExists> <idOrString> <createOwner> <createMode> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<likeOpt> ::= 
<showStmt> ::= R_SHOW R_DATABASES <likeOpt> 
<stmt> ::= <showStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<useStmt> ::= R_USE ID 
<stmt> ::= <useStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<ifNotExists> ::= 
<idOrString> ::= ID 
<types> ::= T_INTEGER 
<primaryOpt> ::= R_PRIMARY R_KEY 
<colOptions> ::= <primaryOpt> 
<colOptionsList> ::= <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<literal> ::= INTEGER 
<literalList> ::= <literalList> S_COMA <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_DECIMAL <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<types> ::= T_INTEGER 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<inheritsOpt> ::= 
<createOpts> ::= R_TABLE <ifNotExists> <idOrString> S_PARIZQ <createTableList> S_PARDER <inheritsOpt> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<ifNotExists> ::= 
<idOrString> ::= ID 
<types> ::= T_INTEGER 
<nullOpt> ::= R_NOT R_NULL 
<colOptions> ::= <nullOpt> 
<colOptionsList> ::= <colOptions> 
<primaryOpt> ::= R_PRIMARY R_KEY 
<colOptions> ::= <primaryOpt> 
<colOptionsList> ::= <colOptionsList> <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<constrName> ::= 
<constraintOpt> ::= <constrName> R_UNIQUE 
<colOptions> ::= <constraintOpt> 
<colOptionsList> ::= <colOptions> 
<nullOpt> ::= R_NOT R_NULL 
<colOptions> ::= <nullOpt> 
<colOptionsList> ::= <colOptionsList> <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<nullOpt> ::= R_NOT R_NULL 
<colOptions> ::= <nullOpt> 
<colOptionsList> ::= <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<types> ::= T_DATE 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<inheritsOpt> ::= 
<createOpts> ::= R_TABLE <ifNotExists> <idOrString> S_PARIZQ <createTableList> S_PARDER <inheritsOpt> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<ifNotExists> ::= 
<idOrString> ::= ID 
<types> ::= T_INTEGER 
<nullOpt> ::= R_NOT R_NULL 
<colOptions> ::= <nullOpt> 
<colOptionsList> ::= <colOptions> 
<primaryOpt> ::= R_PRIMARY R_KEY 
<colOptions> ::= <primaryOpt> 
<colOptionsList> ::= <colOptionsList> <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<inheritsOpt> ::= 
<createOpts> ::= R_TABLE <ifNotExists> <idOrString> S_PARIZQ <createTableList> S_PARDER <inheritsOpt> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<ifExists> ::= 
<idOrString> ::= ID 
<dropStmt> ::= R_DROP R_TABLE <ifExists> <idOrString> 
<stmt> ::= <dropStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<ifNotExists> ::= 
<idOrString> ::= ID 
<types> ::= T_INTEGER 
<nullOpt> ::= R_NOT R_NULL 
<colOptions> ::= <nullOpt> 
<colOptionsList> ::= <colOptions> 
<primaryOpt> ::= R_PRIMARY R_KEY 
<colOptions> ::= <primaryOpt> 
<colOptionsList> ::= <colOptionsList> <colOptions> 
<createColumns> ::= <colOptionsList> 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTable> 
<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<createColumns> ::= 
<createTable> ::= ID <types> <createColumns> 
<createTableList> ::= <createTableList> S_COMA <createTable> 
<inheritsOpt> ::= 
<createOpts> ::= R_TABLE <ifNotExists> <idOrString> S_PARIZQ <createTableList> S_PARDER <inheritsOpt> 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<stmt> ::= <createStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<paramsColumn> ::= 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= DECIMAL 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<insertStmt> ::= R_INSERT R_INTO ID <paramsColumn> R_VALUES S_PARIZQ <paramsList> S_PARDER 
<stmt> ::= <insertStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
<paramsColumn> ::= 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= DECIMAL 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<insertStmt> ::= R_INSERT R_INTO ID <paramsColumn> R_VALUES S_PARIZQ <paramsList> S_PARDER 
<stmt> ::= <insertStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
