
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ALL ALTER AND AS ASC ASTERISCO AVG BACKSPACE BARRA BETWEEN BIGINT BOLEANO CADENA CHAR CHARACTER CHECK COLUMN COMA CONSTRAINT COUNT CREATE CURRENT DATABASE DATABASES DAY DECIMAL DECIMALVALOR DEFAULT DELETE DESC DIFERENTE DIFERENTELL DISTINCT DOUBLE DROP ENTERO ENUM EXCEPT EXISTS FALSE FECHA FEED FIRST FOREIGN FROM FULL GREATEST GROUP GUION HAVING HOUR ID IF IGUAL ILIKE IN INHERITS INNER INSERT INTEGER INTERSECT INTERVAL INTO IS ISNULL JOIN LAST LEAST LEFT LIKE LIMIT LLAVEDER LLAVEIZQ MAS MAX MAYORIGUALQUE MAYORQUE MENORIGUALQUE MENORQUE MIN MINUTE MODE MONEY MONTH NATURAL NEWLINE NOT NOTNULL NULL NULLS NUMERIC OFFSET ON ONLY OR OUTER OWNER PARENDER PARENIZQ PRIMARY PTCOMA PUNTO REAL REFERENCES RENAME REPLACE RETURN RETURNING RIGHT SECOND SELECT SET SIMILAR SMALLINT SUBSTRING SUM TAB TABLE TEXT TIME TIMESTAMP TO TRUE TYPE UNION UNIQUE UNKNOWN UPDATE USING VALUES VARCHAR VARYING WHERE YEAR ZONEinit            : instruccionesinstrucciones    : FECHA'
    
_lr_action_items = {'FECHA':([0,],[3,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','gramatica.py',230),
  ('instrucciones -> FECHA','instrucciones',1,'p_instrucciones_lista','gramatica.py',233),
]
