<literal> ::= INTEGER 
<datatype> ::= <literal> 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<expComp> ::= <datatype> OL_MAYORQUE <datatype> 
<boolean> ::= <expComp> 
<expBool> ::= <boolean> 
<expBool> ::= S_PARIZQ <expBool> S_PARDER 
<literal> ::= R_TRUE 
<datatype> ::= <literal> 
<literal> ::= R_FALSE 
<datatype> ::= <literal> 
<expComp> ::= <datatype> OL_DISTINTODE <datatype> 
<boolean> ::= <expComp> 
<expBool> ::= <boolean> 
<expBool> ::= S_PARIZQ <expBool> S_PARDER 
<expBool> ::= <expBool> R_OR <expBool> 
<expBool> ::= S_PARIZQ <expBool> S_PARDER 
<expresion> ::= <expBool> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<selectStmt> ::= R_SELECT <selectParams> 
<stmt> ::= <selectStmt> S_PUNTOCOMA 
<stmtList> ::= <stmt> 
