
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPUNTOleftDOSPUNTOSleftCORCHETECERCORCHETEAleftPORleftDIVIDIDOleftPORCENTAJEleftMASMENOSrightUMENOSUMASADD ALTER AND AS BETWEEN BIGINT BOOLEAN CADENA CHAR CHARACTER CHECK COMA CONCAT CONSTRAINT CORCHETEA CORCHETECER CREATE DATABASE DATE DAY DECIMAL DIVIDIDO DOSPUNTOS DOUBLE DROP ENTERO ENUM EXPONENCIAL FALSE FOREIGN FROM HOUR ID IF IGUAL IGUALQUE ILIKE IN INTEGER INTERVAL IS KEY LIKE LLAVDER LLAVIZQ MAS MAYORIGUAL MAYQUE MENORIGUAL MENOS MENQUE MINUTE MONEY MONTH NIGUALQUE NOT NULL NUMDECIMAL NUMERIC OR OWNER PARDER PARIZQ POR PORCENTAJE PRECISION PRIMARY PTCOMA PUNTO REFERENCES RENAME REPLACE SECOND SELECT SET SHOW SIMILAR SMALLINT TABLE TEXT TIME TIMESTAMP TO TRUE TYPE UNIQUE VARCHAR VARYING WHERE YEARinit            : instrucciones\n                        instrucciones : instrucciones instruccion\n\n    instrucciones : instruccioninstruccion : inst_select\n                    instruccion : createdb\n                    inst_select : SELECT POR FROM ID PTCOMAinst_select : SELECT listaid FROM listaid PTCOMAinst_select : SELECT listaid FROM listaidA PTCOMAlistaid : listaid COMA IDlistaid : ID listaidA : listaidA COMA ID IDlistaidA : ID IDcreatedb : CREATE DATABASE ID PTCOMAexpr : MENOS ENTERO %prec UMENOSexpr : MAS ENTERO %prec UMAS'
    
_lr_action_items = {'SELECT':([0,2,3,4,5,8,22,23,24,25,],[6,6,-3,-4,-5,-2,-13,-6,-7,-8,]),'CREATE':([0,2,3,4,5,8,22,23,24,25,],[7,7,-3,-4,-5,-2,-13,-6,-7,-8,]),'$end':([1,2,3,4,5,8,22,23,24,25,],[0,-1,-3,-4,-5,-2,-13,-6,-7,-8,]),'POR':([6,],[9,]),'ID':([6,12,13,14,15,20,26,28,],[10,16,17,20,21,27,28,29,]),'DATABASE':([7,],[12,]),'FROM':([9,10,11,21,],[13,-10,14,-9,]),'COMA':([10,11,18,19,20,21,27,29,],[-10,15,15,26,-10,-9,-12,-11,]),'PTCOMA':([16,17,18,19,20,21,27,29,],[22,23,24,25,-10,-9,-12,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,8,]),'inst_select':([0,2,],[4,4,]),'createdb':([0,2,],[5,5,]),'listaid':([6,14,],[11,18,]),'listaidA':([14,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','gramatica.py',205),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','gramatica.py',211),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones2','gramatica.py',219),
  ('instruccion -> inst_select','instruccion',1,'p_instruccionSELECT','gramatica.py',224),
  ('instruccion -> createdb','instruccion',1,'p_instrucciondb','gramatica.py',229),
  ('inst_select -> SELECT POR FROM ID PTCOMA','inst_select',5,'p_instselect','gramatica.py',234),
  ('inst_select -> SELECT listaid FROM listaid PTCOMA','inst_select',5,'p_instselect2','gramatica.py',240),
  ('inst_select -> SELECT listaid FROM listaidA PTCOMA','inst_select',5,'p_selectAlias','gramatica.py',255),
  ('listaid -> listaid COMA ID','listaid',3,'p_listaId2','gramatica.py',259),
  ('listaid -> ID','listaid',1,'p_listaId3','gramatica.py',266),
  ('listaidA -> listaidA COMA ID ID','listaidA',4,'p_listaId2A','gramatica.py',271),
  ('listaidA -> ID ID','listaidA',2,'p_listaId3A','gramatica.py',279),
  ('createdb -> CREATE DATABASE ID PTCOMA','createdb',4,'p_createdb2','gramatica.py',285),
  ('expr -> MENOS ENTERO','expr',2,'p_expruminus','gramatica.py',291),
  ('expr -> MAS ENTERO','expr',2,'p_expreumas','gramatica.py',296),
]
