
    <INICIO> ::= <INSTRUCCIONES>
    <INSTRUCCIONES> ::= <INSTRUCCIONES> <INSTRUCCION> 
            | <INSTRUCCION>

    <INSTRUCCION> ::= <SELECT> ';'
                  | <INSERT> ';'
                  | <UPDATE> ';'
                  | <DELETE> ';'
                  | <DEFINICION> ';'
                  | <COMBINE_QUERYS> ';'
                  | <ALTER_TABLE> ';'

    <DEFINICION> ::= 'create' 'type' 'as' 'enum' '(' <LISTA_ENUM> ')'
                  | <CREATE_OR_REPLACE> 'database' <COMBINACIONES1>
                  | 'show' 'databases' 'like' 'regex'
                  | 'show' 'databases'
                  | 'alter' 'database' 'id' <ALTER>
                  | 'drop' 'database' 'if' 'exists' 'id'
                  | 'drop' 'database' 'id'
                  | 'drop' 'table' 'id'
                  | 'create' 'table' 'id' '('<COLUMNAS>')' <INHERITS>
                  | 'create' 'table' 'id' '('<COLUMNAS>')'

    <COLUMNAS> ::= <COLUMNA> 
                | <COLUMNAS> ',' <COLUMNA> 

    <COLUMNA> ::= 'id' <TIPO> <DEFAULT> <NULLABLE> <CONSTRAINTS> <CHECKS> 
                | 'id' <TIPO> <DEFAULT> <NULLABLE> <CONSTRAINTS>
                | 'id' <TIPO> <DEFAULT> <NULLABLE> <CHECKS>
                | 'id' <TIPO> <DEFAULT> <NULLABLE>
                | 'id' <TIPO> <DEFAULT> <CONSTRAINTS> <CHECKS>
                | 'id' <TIPO> <DEFAULT> <CONSTRAINTS>
                | 'id' <TIPO> <DEFAULT> <CHECKS>
                | 'id' <TIPO> <DEFAULT>
                | 'id' <TIPO> <NULLABLE> <CONSTRAINTS> <CHECKS>
                | 'id' <TIPO> <NULLABLE> <CONSTRAINTS>
                | 'id' <TIPO> <NULLABLE> <CHECKS>
                | 'id' <TIPO> <NULLABLE>
                | 'id' <TIPO> <CONSTRAINTS> <CHECKS>
                | 'id' <TIPO> <CONSTRAINTS>
                | 'id' <TIPO> <CHECKS>
                | 'id' <TIPO>
                | 'id' <TIPO> 'primary' 'key'
                | 'id' <TIPO> 'references' id
                | 'constraint' id 'check' (<LISTA_CONDICIONES>)
                | 'unique' (<LISTA_IDS>)
                | 'primary' 'key' (<LISTA_IDS>)
                | 'foreign' 'key' (<LISTA_IDS>) 'references' id (<LISTA_IDS>)


    <DEFAULT> ::= 'default' <VALOR>

    <NULLABLE> ::= 'not' 'null'
                | 'null'

    <CONSTRAINTS> ::= 'constraint' id 'unique'
                    | 'unique'

    <CHECKS> ::= 'constraint' id 'check' (<CONDICION>)
                |'check' (<CONDICION>) 

    <CONDICION> ::= <EXPRESION>
                 |  <CONDICION>, <EXPRESION>             

    <LISTA_CONDICIONES> ::= <CONDICIONES>
                        |   <LISTA_CONDICIONES>, <CONDICIONES>            

    <TIPO> ::= 'smallint'
            |  'integer'
            |  'bigint'
            |  'decimal'
            |  'numeric'
            |  'real'
            |  'double' 'precision'
            |  'money'
            |  'character' 'varying' ('numero')
            |  'varchar' ('numero')
            |  'character' ('numero')
            |  'char' ('numero')
            |  'text'
            |  <TIMESTAMP>
            |  'date'
            |  <TIME>
            |  <INTERVAL>
            |  'boolean'

    <TIMESTAMP> ::= 'timestamp' ('numero') 'tmstamp'
                |   'timestamp' 'tmstamp'
                |   'timestamp' ('numero') 
                |   'timestamp' 
                | 'now' '(' ')'

    <TIME> ::= 'time' ('numero') 'tmstamp'
            |  'time' 'tmstamp'
            |  'time' ('numero') 
            |  'time' 

    <INTERVAL> ::= 'interval' <FIELDS> ('numero')
                |  'interval' <FIELDS>
                |  'interval' ('numero')
                |  'interval'
                
    <FIELDS> ::= 'year'
              |  'month'
              |  'day'
              |  'hour'
              |  'minute'
              |  'second'

    <ALTER> ::= 'rename to' id
             | 'owner to' <NEW_OWNER>

    <NEW_OWNER> ::= id
                 | 'current_user'
                 | 'session_user'

    <COMBINACIONES1> ::= 'if' 'not' 'exists' id <COMBINACIONES2>
                      | id <COMBINACIONES2>
                      | id

    <COMBINACIONES2> ::= <OWNER>
                      |<MODE>
                      |<OWNER><MODE>
    <OWNER> ::= 'owner' id
             | 'owner' '=' id

    <MODE> ::= 'mode' entero
            | 'mode' '=' entero

    <CREATE_OR_REPLACE> ::= 'create'
                         | 'create or replace'
                  

    <LISTA_ENUM> ::= <ITEM>
                  | <LISTA_ENUM> ',' <ITEM>
    <ITEM> ::= cadena

    <ALTER_TABLE> ::=  'alter' 'table' id <ALTER_OPTIONS>
                   | 'alter' 'table' id <ALTER_VARCHAR_LISTA>

    <ALTER_OPTION> ::= 'add' 'column' id <TIPO>
                    | 'drop' 'column' id
                    | 'add' 'check' '(' id '<''>' '\'' '\'' ')'
                    | 'add' 'constraint' id 'unique' '('id')'
                    | 'add' 'foreign' 'key' '('<LISTA_IDS>')' 'references' <LISTA_IDS>
                    | 'alter' 'column' id 'set' 'not' 'null' 
                    | 'drop' 'constraint' id
                    
    <ALTER_VARCHAR_LISTA>::= <ALTER_VARCHAR>
                           | <ALTER_VARCHAR_LISTA> ',' <ALTER_VARCHAR>
    
    <ALTER_VARCHAR> ::= 'alter' 'column' id 'type' 'varchar('entero')'

    <INHERITS> ::= 'INHERITS' '('ID')'
    
    <COMBINE_QUERYS> ::= <SELECT> <CMB> <SELECT>

    <CMB> ::= 'union' 'all'
        |     'union'
        |     'intersect' 'all'
        |     'intersect'
        |     'except' 'all'
        |     'except'

    <SELECT> ::= 'select' <SELECT_LIST> 'from' <TABLAS> <FILTRO> <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <FILTRO> 
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <LIMITS> <OFFSET> <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <LIMITS> <OFFSET>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <LIMITS>  <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <LIMITS> 
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <OFFSET> <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> <OFFSET>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS>  <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <ORDERS> 
              | 'select' <SELECT_LIST> 'from' <TABLAS> <LIMITS> <OFFSET> <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <LIMITS> <OFFSET>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <LIMITS>  <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <LIMITS> 
              | 'select' <SELECT_LIST> 'from' <TABLAS> <OFFSET> <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS> <OFFSET>
              | 'select' '*' 'from' <TABLAS>  <FILTRO> <JOIN>
              | 'select' '*' 'from' <TABLAS>  <FILTRO>
              | 'select' 'distinct' 'id' 'from'  <TABLAS> <FILTRO> <JOIN>
              | 'select' 'distinct' 'id' 'from'  <TABLAS> <FILTRO>
              | 'select' 'substring' '(' 'id' ',' 'entero' ',' 'entero' ')'  <TABLAS> <FILTRO> <JOIN>
              | 'select' 'substring' '(' 'id' ',' 'entero' ',' 'entero' ')'  <TABLAS> <FILTRO>
              | 'select' <SELECT_LIST> 'from' <TABLAS>   <JOIN>
              | 'select' <SELECT_LIST> 'from' <TABLAS>  
              | 'select' '*' 'from' <TABLAS>   <JOIN>
              | 'select' '*' 'from' <TABLAS>  
              | 'select' 'distinct' 'id' 'from' <TABLAS>   <JOIN>
              | 'select' 'distinct' 'id' 'from' <TABLAS>  
              | 'select' 'substring' '(' 'id' ',' 'entero' ',' 'entero' ')'  <TABLAS>  <JOIN>
              | 'select' 'substring' '(' 'id' ',' 'entero' ',' 'entero' ')'  <TABLAS> 
              | 'select' <FUNCIONES_MATEMATICAS> 'as' 'id' <JOIN>
              | 'select' <FUNCIONES_MATEMATICAS> 'as' 'id'
              | 'select' <FUNCIONES_MATEMATICAS> <JOIN>
              | 'select' <FUNCIONES_MATEMATICAS>

    <JOIN> ::= 'id' <JOIN_TYPE> 'join' 'id' 'on' <PREDICADO>
             | 'id' <JOIN_TYPE> 'join' 'id' 'using' '(' 'join' <LISTA_IDS> ')'
             | 'id' 'natural'<JOIN_TYPE> 'join' 'id'

    <JOIN_TYPE> ::= 'inner'
                |   <OUTER>

    <OUTER> ::= 'left' 'outer'
              | 'right' 'outer'
              | 'full' 'outer'
              | 'left'
              | 'right' 
              | 'full' 

    <FUNCIONES_MATEMATICAS>::= 'as' '('<EXPRESION>')'
                 | 'acos' '('<EXPRESION>')'
                 | 'acosd' '('<EXPRESION>')'
                 | 'asin' '('<EXPRESION>')'
                 | 'asind' '('<EXPRESION>')'
                 | 'atan' '('<EXPRESION>')'
                 | 'atand' '('<EXPRESION>')'
                 | 'atan2' '('<EXPRESION>','<EXPRESION>')'
                 | 'atan2d' '('<EXPRESION>','<EXPRESION>')'
                 | 'cos' '('<EXPRESION>')'
                 | 'cosd' '('<EXPRESION>')'
                 | 'cot' '('<EXPRESION>')'
                 | 'cotd' '('<EXPRESION>')'
                 | 'sin' '('<EXPRESION>')'
                 | 'sind' '('<EXPRESION>')'
                 | 'tan' '('<EXPRESION>')'
                 | 'tand' '('<EXPRESION>')'
                 | 'cosh' '('<EXPRESION>')'
                 | 'sinh' '('<EXPRESION>')'
                 | 'tanh' '('<EXPRESION>')'
                 | 'acosh' '('<EXPRESION>')'
                 | 'asinh' '('<EXPRESION>')'
                 | 'atanh' '('<EXPRESION>')'
                 | 'abs' '('<EXPRESION>')'
                 | 'cbrt' '('<EXPRESION>')'
                 | 'ceil' '('<EXPRESION>')'
                 | 'ceiling' '('<EXPRESION>')'
                 | 'degrees' '('<EXPRESION>')'
                 | 'div' '('<EXPRESION>','<EXPRESION>')'
                 | 'exp' '('<EXPRESION>')'
                 | 'factorial' '('<EXPRESION>')'
                 | 'floor' '('<EXPRESION>')'
                 | 'gcd' '('<EXPRESION>')'
                 | 'ln' '('<EXPRESION>')'
                 | 'log' '('<EXPRESION>')'
                 | 'mod' '('<EXPRESION>',' <EXPRESION>')'
                 | 'pi' '('')'
                 | 'power' '('<EXPRESION>',' <EXPRESION>')'
                 | 'radians' '('<EXPRESION>')'
                 | 'round' '('<EXPRESION>')'
                 | 'sign' '(' <TIPO_NUMERO> ')'
                 | 'sqrt' '(' <TIPO_NUMERO> ')'
                 | 'width_bucket' '(' <LISTA_NUMEROS> ')'
                 | 'trunc' '(' <TIPO_NUMERO> ',' 'numero' ')'
                 | 'trunc' '(' <TIPO_NUMERO> ')'
                 | 'random' '(' ')'
                 | 'square_root' <TIPO_NUMERO> /* VALOR DEL TOKEN square_root: | */
                 | 'cube_root' <TIPO_NUMERO> /* VALOR DEL TOKEN cube_root: || */
                 | <TIPO_NUMERO> 'bitwise_and' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_and: & */
                 | <TIPO_NUMERO> 'bitwise_or' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_or: | */
                 | <TIPO_NUMERO> 'bitwise_xor' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_xor: # */
                 | 'bitwise_not' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_not: ~ */
                 | <TIPO_NUMERO> 'bitwise_shift_left' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_shift_left: << */
                 | <TIPO_NUMERO> 'bitwise_shift_right' <TIPO_NUMERO> /* VALOR DEL TOKEN bitwise_shift_right: >> */

    <LISTA_NUMEROS> ::= <TIPO_NUMERO>
                     |  <LISTA_NUMEROS> ',' <TIPO_NUMERO>
    
    <TIPO_NUMERO> ::= 'numero'
                  |   'decimal'

    <LISTA_TABLAS> ::= <TABLA><ALIAS>
                    | <TABLA>

    <TABLA> ::= 'id' 
             | <SUBQUERY>
            
    <ALIAS> ::= 'as' 'id'
             | 'id'

    <FILTRO>::= <WHERE><GROUP_BY><HAVING>
              |<WHERE><GROUP_BY>
              |<WHERE>

    <HAVING> ::= 'having' <EXPRESION>

    <WHERE> ::= 'where' <PREDICADO>

    <GROUP_BY> ::= <LISTA_IDS>

    <ORDERS> ::= <ORDERBY>
                |<ORDERS> ',' <ORDERBY>

    <ORDERBY> ::= 'order' 'by' <EXPRESION> <ASC_DEC> <NULLS>
                | 'order' 'by' <EXPRESION> <ASC_DEC>
                | 'order' 'by' <EXPRESION> <NULLS>
                | 'order' 'by' <EXPRESION> 

    <ASC_DEC> ::= 'asc'
                | 'desc'

    <NULLS> ::= 'nulls' <FIRST_LAST>

    <FIRST_LAST> ::= 'first'
                |    'last'

    <LIMITS> ::= 'limit' <LIMITC>

    <LIMITC> ::= 'numero'
                |'all'

    <OFFSET> ::= 'offset' 'numero'

    <PREDICADO> ::= <PREDICADO> '<' <PREDICADO>
                 | <PREDICADO> '>' <PREDICADO>
                 | <PREDICADO> '<=' <PREDICADO>
                 | <PREDICADO> '>=' <PREDICADO>
                 | <PREDICADO> '=' <PREDICADO>
                 | <PREDICADO> '< >' <PREDICADO>
                 | <PREDICADO> '!=' <PREDICADO>
                 | <PREDICADO> 'between' <PREDICADO> 'and' <PREDICADO>
                 | <PREDICADO> 'not' 'between' <PREDICADO> 'and' <PREDICADO>
                 | <PREDICADO> 'between' 'symmetric' <PREDICADO> 'and' <PREDICADO>
                 | <PREDICADO> 'not' 'between' 'symmetric' <PREDICADO> 'and' <PREDICADO>
                 | <PREDICADO> 'is' 'distinct' 'from' <PREDICADO>
                 | <PREDICADO> 'is' 'not' 'distinct' 'from' <PREDICADO>
                 | <PREDICADO> 'is' 'null'
                 | <PREDICADO> 'is' 'not' 'null'
                 | <PREDICADO> 'isnull'
                 | <PREDICADO> 'notnull'
                 | <PREDICADO> 'is' 'true'
                 | <PREDICADO> 'is' 'not' 'true'
                 | <PREDICADO> 'is' 'false'
                 | <PREDICADO> 'is' 'not' 'false'
                 | <PREDICADO> 'is' 'unknown'
                 | <PREDICADO> 'is' 'not' 'unknown'
                 | <STR_FUNCTIONS>
                 | 'cadena'
                 | 'numero'
                 | 'decimal'
                 | 'abs' '('<EXPRESION>')'
                 | 'cbrt' '('<EXPRESION>')'
                 | 'ceil' '('<EXPRESION>')'
                 | 'ceiling' '('<EXPRESION>')'
                 | 'degrees' '('<EXPRESION>')'
                 | 'div' '('<EXPRESION>','<EXPRESION>')'
                 | 'exp' '('<EXPRESION>')'
                 | 'factorial' '('<EXPRESION>')'
                 | 'floor' '('<EXPRESION>')'
                 | 'gcd' '('<EXPRESION>')'
                 | 'ln' '('<EXPRESION>')'
                 | 'log' '('<EXPRESION>')'
                 | 'mod' '('<EXPRESION>',' <EXPRESION>')'
                 | 'pi' '('')'
                 | 'power' '('<EXPRESION>',' <EXPRESION>')'
                 | 'radians' '('<EXPRESION>')'
                 | 'round' '('<EXPRESION>')'
                 | 'sign' '(' <TIPO_NUMERO> ')'
                 | 'sqrt' '(' <TIPO_NUMERO> ')'
                 | 'width_bucket' '(' <LISTA_NUMEROS> ')'
                 | 'trunc' '(' <TIPO_NUMERO> ',' 'numero' ')'
                 | 'trunc' '(' <TIPO_NUMERO> ')'
                 | 'random' '(' ')'
                 | <TIMESTAMP>


    <SELECT_LIST> ::= <SELECT_ITEM>
                    | <SELECT_LIST> ',' <SELECT_ITEM>

    <SELECT_ITEM>::=  'id'
                  | 'id' '.' 'id'
                  | <COUNT>
                  | <AGGREGATE_F>
                  | <SUBQUERY>
                  | <CASE>
                  | <GREATEST>
                  | <LEAST>


    <COUNT> ::= 'count' '(' '*' ')'
             |  'count' '(' 'id' ')'
             |  'count' '(' 'distinct' 'id' ')'
    
    <AGGREGATE_F> ::= 'sum' '(' 'id' ')'
                |     'avg' '(' 'id' ')'
                |     'max' '(' 'id' ')'
                |     'min' '(' 'id' ')'

    <CASE> ::= 'case' <SUBCASE> <ELSE_CASE> 'end'
             | 'case' <SUBCASE> 'end'

    <GREATEST> ::= 'greatest' '(' <LISTA_EXP>')'

    <LEAST> ::= 'least' '(' <LISTA_EXP> ')'

    <SUBCASE> ::= <WHEN_CASE>
                | <SUBCASE> <WHEN_CASE>

    <WHEN_CASE> ::= 'when' <PREDICADO> 'then' <EXPRESION>

    <ELSE_CASE> ::= 'else' <EXPRESION>

    <SUBQUERY> ::= '('<SELECT>')'

    <INSERT> ::= 'insert' 'into'  'id' 'values' '('<LISTA_EXP>')'

    <LISTA_EXP> ::= <EXPRESION>
               | <LISTA_EXP> ',' <EXPRESION>


    <PARAMETROS> ::= '(' <LISTA_IDS> ')'

    <LISTA_IDS> ::= <LISTA_IDS> ',' 'ID'  
             | 'ID'

    <EXPRESION> ::= 'not' <EXPRESION>
                | '-'   <EXPRESION>
                | '<>'  <EXPRESION>
                | <EXPRESION> 'and'  <EXPRESION>
                | <EXPRESION> 'or'   <EXPRESION>
                | <EXPRESION> '='  <EXPRESION>
                | <EXPRESION> '!='  <EXPRESION>
                | <EXPRESION> '>='  <EXPRESION>
                | <EXPRESION> '<='  <EXPRESION> 
                | <EXPRESION>  '>'  <EXPRESION>
                | <EXPRESION>  '<'  <EXPRESION>
                | <EXPRESION>  '+'  <EXPRESION>
                | <EXPRESION>  '-'  <EXPRESION>
                | <EXPRESION>  '*'  <EXPRESION>
                | <EXPRESION>  '/'  <EXPRESION>
                | 'cadena'
                | 'numero'
                | 'decimal'
                | 'id' '.' 'id'
                | 'id'
                | '(' <EXPRESION> ')'
                | 'sum' '(' 'id' ')'
                | <STR_FUNCTIONS>
                | <TIMESTAMP>

    <STR_FUNCTIONS> ::= 'length' '(' 'id' ')'
                    |   'substring' '(' 'id' ',' 'entero' ',' 'entero' ')'
                    |   'trim' '(' 'id' ')'
                    |   'md5' '(' 'cadena' ')'
                    |   'sha256' '(' 'cadena' ')'
                    |   'substr''(' 'id' ',' 'entero' ',' 'entero' ')'
                    |   'get_byte' '(' 'cadena' ':' ':' 'bytea' ',' 'numero' ')'
                    |   'set_byte' '(' 'cadena' ':' ':' 'bytea' ',' 'numero' ',' 'numero' ')'
                    |   'convert' '(' 'cadena' 'as' 'date' ')'
                    |   'convert' '(' 'cadena' 'as' 'integer' ')'
                    |   'encode' '(' 'cadena' ':' ':' 'bytea' ',' 'cadena' ')'
                    |   'decode' '(' 'cadena' ',' 'cadena' ')'

     


    <DELETE> ::= 'delete' 'from' 'id' 'where' <EXPRESION>
         
    <UPDATE> ::= 'update' 'id' 'set' <LISTA_ASIGNACIONES> 'where' <EXPRESION>
 
    <LISTA_ASIGNACIONES> ::=  <LISTA_ASIGNACIONES> ',' 'id' '=' <EXPRESION>
                          |  'id' '=' <EXPRESION>
