<inicio> ::= <codigo>
 
<codigo> ::= <instrucciones_globales_list>
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR <instrucciones_funct_list> BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<tipo> ::= integer
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= integer
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= integer
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR <instrucciones_funct_list> BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<tipo> ::= integer
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR <instrucciones_funct_list> BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<tipo> ::= integer
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= TEXT
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= DATE
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <createTable_options> <cT_options>
 
<cT_options> ::= <llave>
 
<llave> ::= PRIMARY KEY | FOREIGN KEY
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<tipo> ::= TEXT
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= TEXT
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<empty> ::= 
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= DATE
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= integer
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <select_insrt> PTCOMA
 
<select_insrt> ::= SELECT <opcion_select_tm>
 
<opcion_select_tm> ::= <opcion_select_lista> FROM <opciones_sobrenombres> 
 
<opciones_sobrenombres> ::= <opcion_sobrenombre>
 
<opcion_sobrenombre> ::= ID 
 
<opcion_select_lista> ::= <opciones_select_lista>
 
<opciones_select_lista> ::= <opcion_select>
 
<opcion_select> ::= POR
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<delete_insrt> ::= DELETE FROM ID <cond_where> PTCOMA
 
<cond_where> ::= WHERE <expresion_where>
 
<expresion_where> ::= <expresion_logica_w>
 
<expresion_logica_w> ::= <expresion_whereb>
 
<expresion_whereb> ::= 
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<drop_insrt> ::= UPDATE TABLE <lista_drop_id> PTCOMA
 
<cond_where> ::= WHERE <expresion_where>
 
<expresion_where> ::= <expresion_logica_w>
 
<expresion_logica_w> ::= <expresion_whereb>
 
<expresion_whereb> ::= 
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<lista_update> ::= <parametro_update>
 
<lista_update> ::= ID IGUAL <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<empty> ::= 
 
<parametros> ::= <parametro>
 
<parametro> ::= <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<drop_insrt_index> ::= DROP INDEX <lista_drop_id_index> PTCOMA
 
<lista_drop_id_index> ::= ID
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= EXECUTE ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID PARA <lista_parametros_lista> PARC  VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID PARA <lista_parametros_lista> PARC  VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID PARA <lista_parametros_lista> PARC  VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID PARA <lista_parametros_lista> PARC  VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_parametros_lista> ::= <lista_parametros_lista> COMA ID
 
<lista_parametros_lista> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<empty> ::= 
 
<parametros> ::= <parametro>
 
<parametro> ::= <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= VARCHAR PARA ENTERO PARC
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <createTable_options> <cT_options>
 
<cT_options> ::= <llave>
 
<llave> ::= PRIMARY KEY | FOREIGN KEY
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR <instrucciones_funct_list> BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= ELSE <instrucciones_funct_list>
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> MAYOR <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= <arit> DIVISION <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<arit> ::= PARA <expresionPLSQL> PARC
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= <arit> MAS <arit>
 
<arit> ::= ID
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= PARA <expresionPLSQL> PARC
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= <arit> POR <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= <arit> MAS <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= decimal
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= decimal
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<tipo> ::= integer
 
<parametros> ::= <parametro>
 
<parametro> ::= <empty>
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<drop_insrt> ::= UPDATE TABLE <lista_drop_id> PTCOMA
 
<cond_where> ::= WHERE <expresion_where>
 
<expresion_where> ::= <expresion_logica_w>
 
<expresion_logica_w> ::= <expresion_whereb>
 
<expresion_whereb> ::= 
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<expresion_wherea> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= ID
 
<lista_update> ::= <parametro_update>
 
<lista_update> ::= ID IGUAL <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <params> COMA <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR <instrucciones_funct_list> BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= ELSE <instrucciones_funct_list>
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= ID
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= CADENA
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= ELSE <instrucciones_funct_list>
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= ID
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= CADENA
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= 
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<sentencia_if> ::= IF <expresionPLSQL> THEN <instrucciones_funct_list> <else> END IF PTCOMA
 
<else> ::= ELSE <instrucciones_funct_list>
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= ID
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<asignacion> ::= ID DOSPUNTOS IGUAL <expresionPLSQL> PTCOMA
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ENTERO | FLOTANTE
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit> IGUALIGUAL <arit>
 
<arit> ::= CADENA
 
<arit> ::= ID
 
<instrucciones_funct_list> ::= <instrucciones_funct_list> <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::= ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<declaracion> ::=  DECLARE ID <tipo> PTCOMA
 
<tipo> ::= integer
 
<tipo> ::= integer
 
<parametros> ::= <parametros> COMA <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= integer
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= VARCHAR PARA ENTERO PARC
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<insert_insrt> ::= INSERT INTO ID VALUES PARA <lista_datos> PARC PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= NOW PARA PARC
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= VARCHAR PARA ENTERO PARC
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <createTable_options> <cT_options>
 
<cT_options> ::= <llave>
 
<llave> ::= PRIMARY KEY | FOREIGN KEY
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createIndex> ::= CREATE INDEX ID ON ID <opc_index> PTCOMA
 
<empty> ::= 
 
<empty> ::= 
 
<empty> ::= 
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= INTEGER
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= DATE
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= VARCHAR PARA ENTERO PARC
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<cuerpo_createTable> ::= ID <TIPO_DATO_DEF> <createTable_options>
 
<createTable_options> ::= <createTable_options> <cT_options>
 
<cT_options> ::= <llave>
 
<llave> ::= PRIMARY KEY | FOREIGN KEY
 
<createTable_options> ::= <cT_options>
 
<cT_options> ::= <N_null>
 
<N_null> ::= NOT NULL
 
<TIPO_DATO_DEF> ::= INTEGER
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<llamada_funcion> ::= SELECT ID PARA <params> PARC PTCOMA
 
<params> ::= <expresionPLSQL> | <empty>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= CADENA
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<funciones> ::= CREATE FUNCTION ID PARA <parametros> PARC RETURNS <tipo> AS DOLAR DOLAR BEGIN <instrucciones_funct_list> END PTCOMA DOLAR DOLAR LANGUAGE PLPGSQL PTCOMA
 
<instrucciones_funct_list> ::= <instrucciones_funct_sent>
 
<instrucciones_funct_sent> ::= <asignacion> | <declaracion> | <imprimir> | <sentencia_if> 
 
<imprimir> ::= RAISE <lista_imprimir> PTCOMA
 
<lista_imprimir> ::= <sent_imprimir>
 
<set_imprimir> ::= <expresionPLSQL>
 
<expresionPLSQL> ::= <log>
 
<log> ::= <rel>
 
<rel> ::= <arit>
 
<arit> ::= ID
 
<tipo> ::= TEXT
 
<parametros> ::= <parametro>
 
<parametro> ::= ID <tipo>
 
<tipo> ::= TEXT
 
<instrucciones_globales_list> ::= <instrucciones_globales_list><instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<use_database_instr> ::= USE ID PTCOMA
 
<instrucciones_globales_list> ::= <instrucciones_global_sent>
 
<instrucciones_global_sent> ::= <funciones> | <llamada_funcion> | <createDB_insrt> | <show_databases_instr> 
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA