<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <select_uniones> PTOCOMA
 
<select_uniones> ::= <select_uniones> <tipo_union> <select_insrt>
 
<select_insrt> ::= SELECT <opcion_select_tm>
 
<opcion_select_tm> ::= <opcion_select_lista>  FROM <opciones_sobrenombres>
 
<opciones_sobrenombres> ::= <opcion_sobrenombre>
 
<opcion_sobrenombre> ::= ID
 
<opcion_select_lista> ::= <opciones_select_lista>
 
<opciones_select_lista> ::= <opcion_select>
 
<opcion_select> ::= ASTERISCO
 
<tipo_union> ::= UNION
 
<select_uniones> ::= <select_insrt>
 
<select_insrt> ::= SELECT <opcion_select_tm>
 
<opcion_select_tm> ::= <opcion_select_lista>  FROM <opciones_sobrenombres>
 
<opciones_sobrenombres> ::= <opcion_sobrenombre>
 
<opcion_sobrenombre> ::= ID
 
<opcion_select_lista> ::= <opciones_select_lista>
 
<opciones_select_lista> ::= <opcion_select>
 
<opcion_select> ::= ASTERISCO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <select_insrt> PTCOMA
 
<select_insrt> ::= SELECT <opcion_select_tm>
 
<opcion_select_tm> ::= <opcion_select_lista>  FROM <opciones_sobrenombres>
 
<opciones_sobrenombres> ::= <opcion_sobrenombre>
 
<opcion_sobrenombre> ::= ID
 
<opcion_select_lista> ::= <opciones_select_lista>
 
<opciones_select_lista> ::= <opcion_select>
 
<opcion_select> ::= ASTERISCO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <select_insrt> PTCOMA
 
<select_insrt> ::= SELECT <opcion_select_tm>
 
<opcion_select_tm> ::= <opcion_select_lista>  FROM <opciones_sobrenombres>
 
<opciones_sobrenombres> ::= <opcion_sobrenombre>
 
<opcion_sobrenombre> ::= ID
 
<opcion_select_lista> ::= <opciones_select_lista>
 
<opciones_select_lista> ::= <opcion_select>
 
<opcion_select> ::= ASTERISCO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <insert_insrt>
 
<insert_insrt> ::= INSERT INTO ID VALUES PAR_A <lista_datos> PAR_C PTCOMA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <lista_datos> COMA <expresion>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <string_type>
 
<string_type> ::= CADENA
 
<lista_datos> ::= <exclusiva_insert>
 
<exclusiva_insert> ::= <expresion>
 
<expresion> ::= <expresion_dato>
 
<expresion_dato> ::= <expresion_numero>
 
<expresion_numero> ::= ENTERO
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <create_Table_isnrt>
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PAR_A ENTERO PAR_C
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PAR_A ENTERO PAR_C
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= INTEGER
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <create_Table_isnrt>
 
<create_Table_isnrt> ::= CREATE TABLE ID PAR_A <cuerpo_createTable_lista> PAR_C PTCOMA 
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PAR_A ENTERO PAR_C
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable_lista> COMA <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= VARCHAR PAR_A ENTERO PAR_C
 
<cuerpo_createTable_lista> ::= <cuerpo_createTable>
 
<campos_c> ::= ID <TIPO_DATO_DEF>
 
<TIPO_DATO_DEF> ::= INTEGER
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <use_database_instr>
 
<use_database_instr> ::= USE ID PTCOMA
 
<init> ::= <instrucciones>
 
<instrucciones> ::= <instruccion>
 
<instruccion> ::= <createDB_insrt>
 
<createDB_insrt> ::= CREATE DATABASE ID PTCOMA