<literal> ::= INTEGER 
<literalList> ::= <literal> 
<optParams> ::= S_PARIZQ <literalList> S_PARDER 
<types> ::= T_VARCHAR <optParams> 
<typeParam> ::= ID <types> 
<typeParamsList> ::= <typeParam> 
<types> ::= T_INTEGER 
<typeParam> ::= ID <types> 
<typeParamsList> ::= <typeParamsList> S_COMA <typeParam> 
<types> ::= ID 
<types> ::= T_INTEGER 
<funcCall> ::= R_COUNT S_PARIZQ O_PRODUCTO S_PARDER 
<datatype> ::= <funcCall> 
<expresion> ::= <datatype> 
<selectListParams> ::= <expresion> 
<optAlias> ::= 
<selectList> ::= <selectListParams> <optAlias> 
<selectParams> ::= <selectList> 
<optAlias> ::= 
<fromBody> ::= ID <optAlias> 
<tableExp> ::= <fromBody> 
<fromCl> ::= R_FROM <tableExp> 
<whereCl> ::= 
<groupByCl> ::= 
<limitCl> ::= 
<orderByCl> ::= 
<selectStmt> ::= R_SELECT <selectParams> <fromCl> <whereCl> <groupByCl> <limitCl> <orderByCl> 
<expresion> ::= S_PARIZQ <selectStmt> S_PARDER 
<declaration> ::= ID <types> S_IGUAL <expresion> S_PUNTOCOMA 
<declarationList> ::= <declaration> 
<types> ::= T_INTEGER 
<declaration> ::= ID <types> S_PUNTOCOMA 
<declarationList> ::= <declarationList> <declaration> 
<columnName> ::= ID 
<datatype> ::= <columnName> 
<expresion> ::= <datatype> 
<returnStmt> ::= R_RETURN <expresion> 
<plInstruction> ::= <returnStmt> S_PUNTOCOMA 
<plInstructions> ::= <plInstruction> 
<codeBlock> ::= R_DECLARE <declarationList> R_BEGIN <plInstructions> R_END 
<createOpts> ::= R_FUNCTION ID S_PARIZQ <typeParamsList> S_PARDER R_RETURNS <types> R_AS S_DOBLEDOLAR <codeBlock> S_PUNTOCOMA S_DOBLEDOLAR R_LANGUAGE R_PLPGSQL 
<createBody> ::= <createOpts> 
<createStmt> ::= R_CREATE <createBody> 
<fase2_stmt> ::= <createStmt> S_PUNTOCOMA 
<stmt> ::= <fase2_stmt> 
<stmtList> ::= <stmt> 
<init> ::= <stmtList> 
