<useStmt> ::= R_USE ID 
<stmt> ::= <useStmt> S_PUNTOCOMA 
<stmtList> ::= <stmt> 
<idList> ::= ID 
<idList> ::= <idList> S_COMA ID 
<idList> ::= <idList> S_COMA ID 
<idList> ::= <idList> S_COMA ID 
<idList> ::= <idList> S_COMA ID 
<idList> ::= <idList> S_COMA ID 
<paramsColumn> ::= S_PARIZQ <idList> S_PARDER 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= STRING 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<literal> ::= INTEGER 
<datatype> ::= <literal> 
<paramsList> ::= <paramsList> S_COMA <datatype> 
<insertStmt> ::= R_INSERT R_INTO ID <paramsColumn> R_VALUES S_PARIZQ <paramsList> S_PARDER 
<stmt> ::= <insertStmt> S_PUNTOCOMA 
<stmtList> ::= <stmtList> <stmt> 
