-- ARCHIVO DE ENTRADA PARA PRUEBAS
CREATE DATABASE hola;
CREATE DATABASE nueva OWNER = heidy;
CREATE DATABASE nueva2 MODE = 1;
CREATE DATABASE nueva3 OWNER= heidy MODE=2;

CREATE OR REPLACE DATABASE hola;
CREATE OR REPLACE DATABASE nueva OWNER = heidy;
CREATE OR REPLACE DATABASE nueva2 MODE = 1;
CREATE OR REPLACE DATABASE nueva3 OWNER= heidy MODE=2;

CREATE DATABASE IF NOT EXISTS hola;
CREATE DATABASE IF NOT EXISTS nueva OWNER = heidy;
CREATE DATABASE IF NOT EXISTS nueva2 MODE = 1;
CREATE DATABASE IF NOT EXISTS nueva3 OWNER= heidy MODE=2;

SHOW DATABASES;
SHOW DATABASES LIKE "%nuevo%";

ALTER DATABASE hola RENAME TO base;
ALTER DATABASE nueva OWNER TO base2;
ALTER DATABASE nueva2 OWNER TO CURRENT_USER;
ALTER DATABASE nueva3 OWNER TO SESSION_USER;

DROP DATABASE base;
DROP DATABASE IF EXISTS base;


CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

UPDATE weather SET temp_lo = temp_lo+1, temp_hi = temp_lo+15, prcp = cadenita
WHERE city = 'San Francisco' AND date_ = '2003-07-03';

