
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASTERISCO COMA FROM ID PTCOMA SELECTinstruccion : select_insrt select_insrt : SELECT opcion_select_lista FROM ID PTCOMA opcion_select_lista : opcion_select_lista COMA opcion_select opcion_select_lista : opcion_select  opcion_select : ASTERISCO\n                      | ID '
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,2,12,],[0,-1,-2,]),'ASTERISCO':([3,9,],[7,7,]),'ID':([3,8,9,],[5,10,5,]),'FROM':([4,5,6,7,11,],[8,-6,-4,-5,-3,]),'COMA':([4,5,6,7,11,],[9,-6,-4,-5,-3,]),'PTCOMA':([10,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instruccion':([0,],[1,]),'select_insrt':([0,],[2,]),'opcion_select_lista':([3,],[4,]),'opcion_select':([3,9,],[6,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instruccion","S'",1,None,None,None),
  ('instruccion -> select_insrt','instruccion',1,'p_instruccion','sql.py',55),
  ('select_insrt -> SELECT opcion_select_lista FROM ID PTCOMA','select_insrt',5,'p_instruccion_select_insrt','sql.py',59),
  ('opcion_select_lista -> opcion_select_lista COMA opcion_select','opcion_select_lista',3,'p_select_lista','sql.py',62),
  ('opcion_select_lista -> opcion_select','opcion_select_lista',1,'p_opcion_select_lista','sql.py',65),
  ('opcion_select -> ASTERISCO','opcion_select',1,'p_opcion_select','sql.py',68),
  ('opcion_select -> ID','opcion_select',1,'p_opcion_select','sql.py',69),
]
