from execution.executeSentence import executeSentence 
from execution.AST.sentence import *
from execution.AST.expression import *
def up():
	executeSentence(CreateDatabase,CreateDatabase('TEST',True,False,['ROOT', Value(1,1)]))
	executeSentence(CreateDatabase,CreateDatabase('CALIFICA',True,False,['ROOT', Value(1,2)]))
	executeSentence(CreateDatabase,CreateDatabase('CALIFICA2',True,False,['ROOT', Value(1,3)]))
	executeSentence(Use,Use('TEST'))
	executeSentence(CreateTable,CreateTable('TBCALIFICA',[ColumnId('IDITEM',['INTEGER'],{'null': False, 'primary': True}), ColumnId('ITEM',['VARCHAR', 150],{'null': False}), ColumnId('PUNTOS',['DECIMAL'],{'null': False})],None))
	executeSentence(CreateTable,CreateTable('TBUSUARIO',[ColumnId('IDUSUARIO',['INTEGER'],{'null': False, 'primary': True}), ColumnId('NOMBRE',['VARCHAR', 50],None), ColumnId('APELLIDO',['VARCHAR', 50],None), ColumnId('USUARIO',['VARCHAR', 15],{'unique': True, 'null': False}), ColumnId('PASSWORD',['VARCHAR', 15],{'null': False}), ColumnId('FECHACREACION',['DATE'],None)],None))
	executeSentence(CreateTable,CreateTable('TBROLES',[ColumnId('IDROL',['INTEGER'],{'null': False, 'primary': True}), ColumnId('ROL',['VARCHAR', 15],None)],None))
	executeSentence(Select,Select([ExtractFunction('YEAR',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('HOUR',Value(3,'2001-02-16 04:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('HOUR',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('MINUTE',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('SECOND',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('YEAR',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('MONTH',Value(3,'2001-02-16 20I:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('DAY',Value(3,'2001-02-16 20:38:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('MINUTE',Value(3,'2001-02-16 20:03:40'))],False,None,None))
	executeSentence(Select,Select([ExtractFunction('SECOND',Value(3,'2001-02-16 20:03:15'))],False,None,None))
	executeSentence(CreateType,CreateType('AREA',[Value(3,'CONTABILIDAD'), Value(3,'ADMINISTRACION'), Value(3,'VENTAS'), Value(3,'TECNOLOGIA'), Value(3,'FABRICA')]))
	executeSentence(ShowDatabases,ShowDatabases())
	executeSentence(DropDatabase,DropDatabase('CALIFICA2',True))
	executeSentence(DropTable,DropTable('TBROLES'))
	executeSentence(CreateTable,CreateTable('TBROL',[ColumnId('IDROL',['INTEGER'],{'null': False, 'primary': True}), ColumnId('ROL',['VARCHAR', 15],None)],None))
	executeSentence(InsertAll,InsertAll('TBCALIFICA',[Value(1,1), Value(3,'FUNCIONALIDADES BÁSICAS'), Value(2,'2.0')]))
	executeSentence(InsertAll,InsertAll('TBCALIFICA',[Value(1,2), Value(3,'FUNCIONES DATE-EXTRACT'), Value(2,'2.0')]))
	executeSentence(Select,Select([Value(6,'*')],False,[Value(4,'TBCALIFICA')],None))
	executeSentence(CreateTable,CreateTable('TBROLXUSUARIO',[ColumnId('IDROL',['INTEGER'],{'null': False}), ColumnId('IDUSUARIO',['INTEGER'],{'null': False})],None))
	executeSentence(InsertAll,InsertAll('TBROL',[Value(1,1), Value(3,'ADMINISTRADOR')]))
	executeSentence(InsertAll,InsertAll('TBROL',[Value(1,2), Value(3,'ADMIN')]))
	executeSentence(InsertAll,InsertAll('TBROL',[Value(1,3), Value(3,'VENTAS')]))
	executeSentence(Select,Select([Value(6,'*')],False,[Value(4,'TBROL')],None))
	executeSentence(InsertAll,InsertAll('TBCALIFICA',[Value(1,3), Value(3,'TYPE'), Value(2,'2.0')]))
	executeSentence(InsertAll,InsertAll('TBCALIFICA',[Value(1,4), Value(3,'CREATE DATABASE-REPLACE'), Value(2,'3.0')]))
	executeSentence(InsertAll,InsertAll('TBCALIFICA',[Value(1,5), Value(3,'SHOW DATABASE'), Value(2,'2.0')]))
	executeSentence(AlterTableAlterColumnType,AlterTableAlterColumnType('TBUSUARIO','PASSWORD',['VARCHAR', 80]))